name: MicroClazz
version: '1.0-SNAPSHOT'
main: me.tcrs.microClazz.MicroClazz
api-version: '1.21'
author: The_CommanderRS
description: Instantly compile and load Java classes with in-game commands.

commands:
  microclazz:
    description: MicroClazzes Command
    usage: /<command>
